version: '3.8'

services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - website
    environment:
      DOMAINS: 'operator.mattkantor.com -> http://website:80'
      STAGE: 'production'

  website:
    image: operator-website
    command: -vv --error-handler-route=/error-handler --index-route=/home
