version: "3.8"

volumes:
  ssl-certificates:

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    links:
      - website
    volumes:
      - ssl-certificates:/var/lib/https-portal
    environment:
      DOMAINS: operator.mattkantor.com -> http://website:80
      STAGE: production
      CUSTOM_NGINX_SERVER_CONFIG_BLOCK: proxy_buffering off; # For the streaming example.

  website:
    image: operator-website
    command: -vv --error-handler-route=/error-handler --index-route=/home
